import {createServer} from '../server/index.js';
import {createServer as createVite} from 'vite';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const app=createServer({dbPath:':memory:'});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
const origin='http://127.0.0.1:'+app.server.address().port;
let vite=null;let webOrigin=origin;if(process.env.ERP_TEST_MODE!=='production'){vite=await createVite({server:{host:'127.0.0.1',port:0,strictPort:false}});await vite.listen();webOrigin='http://127.0.0.1:'+vite.httpServer.address().port;}
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1080}});const page=await context.newPage();const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await context.route('**/api/**',async route=>{const req=route.request();const path=new URL(req.url()).pathname+new URL(req.url()).search;const headers={...req.headers(),origin};delete headers.host;const result=await route.fetch({url:origin+path,headers});await route.fulfill({response:result});});
let count=0;const pass=label=>{count++;console.log('PASS '+label)};
const go=async key=>{await page.locator('.sidebar [data-page="'+key+'"]').evaluate(el=>{const details=el.closest('details');if(details)details.open=true;});await page.locator('.sidebar [data-page="'+key+'"]').click();await page.waitForFunction(k=>location.hash==='#'+k,key);await page.waitForTimeout(180);};
try{
 const privateFile=await fetch(webOrigin+'/data/erp.sqlite');if(vite)assert.equal(privateFile.status,403);else assert.match(privateFile.headers.get('content-type'),/text\/html/);pass('File database không được phục vụ qua HTTP');
 await page.goto(webOrigin);await page.locator('#auth-form').waitFor();
 await page.locator('[name=name]').fill('Minh Anh');await page.locator('[name=username]').fill('browser-admin');await page.locator('[name=password]').fill('browser-test-password-123');await page.getByRole('button',{name:'Tạo hệ thống ERP',exact:true}).click();
 await page.locator('.stat-grid').waitFor({timeout:15000});assert.match(await page.locator('h1').textContent(),/Tổng quan/);pass('Khởi tạo ERP, đăng nhập và dashboard dữ liệu mẫu');
 await page.screenshot({path:'/tmp/gems-erp-dashboard.png',fullPage:true});
 await go('buildings');await page.locator('#add-record').click();await page.locator('[name=name]').fill('Tòa nhà kiểm thử');await page.locator('[name=legalEntityId]').selectOption({label:'Gems Office Demo'});await page.locator('[name=address]').fill('Địa chỉ kiểm thử');await page.locator('[name=model]').selectOption('Master Lease');await page.locator('[name=area]').fill('500');await page.getByRole('button',{name:'Lưu dữ liệu',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.locator('tbody').getByText('Tòa nhà kiểm thử',{exact:true}).waitFor();pass('CRUD tòa nhà lưu trên database');
 await go('tenants');await page.locator('#add-record').click();await page.locator('[name=name]').fill('Khách kiểm thử');await page.locator('[name=email]').fill('test@example.com');await page.getByRole('button',{name:'Lưu dữ liệu',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.locator('tbody').getByText('Khách kiểm thử',{exact:true}).waitFor();await page.reload();await page.locator('tbody').getByText('Khách kiểm thử',{exact:true}).waitFor();pass('Khách thuê được giữ sau tải lại');
 await go('invoices');await page.locator('[data-action=pay]').first().click();await page.locator('[name=amount]').fill('1000');await page.locator('[name=method]').selectOption('Chuyển khoản');await page.getByRole('button',{name:'Xác nhận',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open);pass('Thu một phần hóa đơn qua giao diện');
 await page.locator('[data-detail]').first().click();await page.getByText('Chi tiết hóa đơn · số liệu đã chụp').waitFor();await page.locator('#close-modal').click();pass('Xem snapshot hóa đơn và lịch sử thu');
 await go('tasks');await page.locator('[data-action=reject]').first().click();await page.locator('[name=reason]').fill('Bổ sung hồ sơ');await page.getByRole('button',{name:'Xác nhận',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.getByText('Bị trả lại',{exact:true}).waitFor();pass('Công việc được trả lại và có nút gửi duyệt lại');
 await go('appraisals');await page.locator('[data-model]').first().click();await page.locator('.scenario-grid').waitFor();assert.equal(await page.locator('.scenario').count(),3);assert.equal(await page.locator('.model-timeline tbody tr').count(),120);await page.locator('#close-modal').click();pass('Thẩm định 120 tháng và 3 kịch bản');
 await go('modules');assert.equal(await page.locator('.module-table tbody tr').count(),38);assert.equal(await page.locator('.requirements-list details').count(),41);pass('38 module và 41 yêu cầu được đối chiếu');
 await go('payroll');await page.locator('[data-payroll]').first().click();await page.getByText('Thưởng chạy thử:',{exact:false}).waitFor();await page.locator('#close-modal').click();pass('Chạy thử lương KPI và xem cách tính');
 await go('ledger');await page.getByText('Bảng cân đối tài khoản',{exact:true}).waitFor();pass('Sổ cái và cân đối Nợ/Có qua giao diện');
 await go('inventoryItems');await page.locator('[data-action=receive]').first().click();await page.locator('[name=quantity]').fill('10');await page.locator('[name=notes]').fill('Nhập kiểm thử');await page.getByRole('button',{name:'Xác nhận',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.waitForTimeout(200);pass('Nhập kho vật tư qua giao diện');
 await go('purchaseOrders');await page.locator('[data-action=approve]').first().click();await page.getByRole('button',{name:'Xác nhận',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.locator('[data-action=receive]').first().waitFor();pass('Duyệt đề nghị mua sắm');

 await go('projectFlows');await page.locator('#add-record').click();await page.locator('[name=name]').fill('Quy trình dự án minh họa');await page.locator('[name=buildingId]').selectOption({index:1});await page.locator('[name=template]').selectOption('Master Lease 10 năm');await page.locator('[name=ownerId]').selectOption({label:'Trần Hoàng Nam · PKD'});await page.getByRole('button',{name:'Lưu dữ liệu',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.locator('tbody').getByText('Quy trình dự án minh họa',{exact:true}).waitFor();await page.locator('[data-detail]').first().click();assert.equal(await page.locator('.flow-steps li').count(),7);await page.locator('#close-modal').click();pass('Vòng đời dự án 7 bước và công việc tự sinh');
 await go('qualityChecks');await page.locator('#add-record').click();await page.locator('[name=buildingId]').selectOption({index:1});await page.locator('[name=employeeId]').selectOption({label:'Lê Quốc Bảo · BQL'});await page.locator('[name=serviceRole]').selectOption('Kỹ thuật');await page.locator('[name=score]').fill('90');await page.locator('[name=notes]').fill('Kiểm tra chất lượng thiết bị');await page.locator('[name=photo]').setInputFiles({name:'evidence.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6JbUAAAAASUVORK5CYII=','base64')});await page.locator('[name=latitude]').fill('10.7');await page.locator('[name=longitude]').fill('106.6');await page.getByRole('button',{name:'Lưu dữ liệu',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.locator('tbody').getByText('90',{exact:true}).waitFor();await page.locator('[data-detail]').first().click();await page.locator('.quality-photo').waitFor();await page.locator('#close-modal').click();pass('Phiếu chất lượng lưu ảnh và vị trí GPS');

 await go('audit');await page.locator('[data-log]').first().click();assert.equal(await page.locator('pre').count(),2);await page.locator('#close-modal').click();pass('Nhật ký before/after');
 await go('dashboard');await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await page.screenshot({path:'/tmp/gems-erp-mobile.png',fullPage:true});await page.locator('#mobile-menu').click();await page.locator('.sidebar summary').filter({hasText:'VẬN HÀNH'}).click();await page.locator('.sidebar [data-page=tickets]').click();await page.locator('#add-record').waitFor();pass('Dashboard và nhập yêu cầu trên điện thoại');
 assert.deepEqual(errors,[]);pass('Không có lỗi JavaScript trên trình duyệt');
 console.log(`Completed: ${count} browser checks passed; 0 failed.`);
}finally{await browser.close();if(vite)await vite.close();await app.close();}
