export const roles = {admin:'Quản trị viên', manager:'Trưởng phòng', accountant:'Kế toán', staff:'Nhân viên', technician:'Kỹ thuật', tenant:'Khách thuê'};
const f = (key,label,type='text',extra={}) => ({key,label,type,...extra});
const ref = (key,label,collection,extra={}) => f(key,label,'select',{ref:collection,...extra});
const opt = (key,label,options,extra={}) => f(key,label,'select',{options,...extra});
const required = {required:true};
const base = (label,singular,group,icon,prefix,fields,columns,writers=['admin','manager']) => ({label,singular,group,icon,prefix,fields,columns,writers});
export const schemas = {
 accounts:base('Hệ thống tài khoản','tài khoản kế toán','KẾ TOÁN & MUA SẮM','list','TK',[f('accountNumber','Số tài khoản','text',required),f('name','Tên tài khoản','text',required),opt('type','Loại',['Tài sản','Nợ phải trả','Doanh thu','Chi phí'],required)],['accountNumber','name','type'],['admin','accountant']),
 journalEntries:base('Sổ nhật ký kế toán','bút toán','KẾ TOÁN & MUA SẮM','receipt','BT',[],['name','date','legalEntityId','totalDebit','totalCredit'],[]),
 vendors:base('Nhà cung cấp','nhà cung cấp','KẾ TOÁN & MUA SẮM','briefcase','NCC',[f('name','Tên nhà cung cấp','text',required),f('taxCode','Mã số thuế'),f('contact','Người liên hệ'),f('email','Email','email'),f('phone','Điện thoại')],['name','taxCode','contact','phone']),
 purchaseOrders:base('Đề nghị mua sắm','đề nghị mua','KẾ TOÁN & MUA SẮM','credit','PO',[f('name','Nội dung mua sắm','text',required),ref('vendorId','Nhà cung cấp','vendors',required),ref('buildingId','Tòa nhà','buildings',required),ref('legalEntityId','Pháp nhân','legalEntities',required),f('quantity','Số lượng','number',{min:1,...required}),f('unitPrice','Đơn giá (VNĐ)','number',{min:1,...required}),f('taxRate','Thuế suất (%)','number',{min:0,max:100}),f('dueDate','Ngày cần hàng','date',required)],['name','vendorId','quantity','unitPrice','status'],['admin','manager','staff','technician']),
 inventoryItems:base('Kho vật tư','vật tư','KẾ TOÁN & MUA SẮM','grid','VT',[f('name','Tên vật tư','text',required),ref('buildingId','Kho tại tòa nhà','buildings',required),f('unit','Đơn vị tính','text',required),f('unitCost','Giá tham chiếu (VNĐ)','number',{min:0}),f('minimumStock','Tồn tối thiểu','number',{min:0})],['name','buildingId','quantity','unit','minimumStock'],['admin','manager','technician']),
 stockMovements:base('Lịch sử nhập xuất','giao dịch kho','KẾ TOÁN & MUA SẮM','repeat','KHO',[],['name','buildingId','direction','quantity','date'],[]),
 legalEntities:base('Pháp nhân','pháp nhân','NỀN TẢNG','briefcase','PN',[f('name','Tên pháp nhân','text',required),f('taxCode','Mã số thuế'),f('address','Địa chỉ')],['name','taxCode','address']),
 buildings:base('Tòa nhà & dự án','tòa nhà','TÀI SẢN & KHÁCH THUÊ','building','DA',[f('name','Tên tòa nhà','text',required),ref('legalEntityId','Pháp nhân','legalEntities',required),f('address','Địa chỉ'),opt('model','Mô hình',['Master Lease','Managed Office','Setup'],required),f('area','Diện tích (m²)','number',{min:1,...required}),f('floors','Số tầng','number',{min:1}),f('monthlyCost','Chi phí cố định/tháng (VNĐ)','number',{min:0})],['name','legalEntityId','model','area']),
 units:base('Mặt bằng','mặt bằng','TÀI SẢN & KHÁCH THUÊ','grid','MB',[f('name','Tên mặt bằng','text',required),ref('buildingId','Tòa nhà','buildings',required),f('floor','Tầng','number',{min:0,...required}),f('area','Diện tích (m²)','number',{min:1,...required}),f('askingRent','Giá chào thuê/m² (VNĐ)','number',{min:0}),opt('status','Trạng thái',['Trống','Đang thuê','Bảo trì'],required)],['name','buildingId','floor','area','status']),
 tenants:base('Khách thuê & CRM','khách thuê','TÀI SẢN & KHÁCH THUÊ','users','KH',[f('name','Tên doanh nghiệp','text',required),f('taxCode','Mã số thuế'),f('contact','Người liên hệ'),f('email','Email','email'),f('phone','Điện thoại'),f('notes','Ghi chú chăm sóc','textarea')],['name','contact','phone','email']),
 contracts:base('Hợp đồng thuê','hợp đồng','TÀI SẢN & KHÁCH THUÊ','file','HD',[ref('unitId','Mặt bằng','units',required),ref('tenantId','Khách thuê','tenants',required),ref('legalEntityId','Pháp nhân xuất hóa đơn','legalEntities',required),f('startDate','Ngày bắt đầu','date',required),f('endDate','Ngày kết thúc','date',required),f('freeUntil','Miễn phí thuê đến hết ngày','date'),f('deposit','Tiền cọc (VNĐ)','number',{min:0}),f('renewal','Lần gia hạn','number',{min:1}),f('noticeMonths','Số tháng báo trước','number',{min:0}),f('penaltyWithNotice','Bồi thường đủ báo trước (tháng thuê)','number',{min:0}),f('penaltyWithoutNotice','Bồi thường thiếu báo trước (tháng thuê)','number',{min:0}),opt('taxInvoice','Nhận hóa đơn thuế',['Có','Không']),f('notes','Ghi chú','textarea')],['code','tenantId','unitId','startDate','endDate','status'],['admin','manager','accountant']),
 prices:base('Lộ trình giá & phí','đơn giá','TÀI CHÍNH','tag','GIA',[ref('contractId','Hợp đồng','contracts',required),opt('fee','Loại phí',['rent','service','electricity','water','parking','signage','overtime'],required),opt('basis','Cách tính',['area','flat','usage'],required),f('unitPrice','Đơn giá','number',{min:0,...required}),opt('currency','Tiền tệ',['VND','USD'],required),f('effectiveDate','Ngày hiệu lực','date',required)],['contractId','fee','unitPrice','currency','effectiveDate'],['admin','accountant']),
 exchangeRates:base('Tỷ giá theo hợp đồng','tỷ giá','TÀI CHÍNH','repeat','FX',[ref('contractId','Hợp đồng','contracts',required),f('effectiveDate','Ngày hiệu lực','date',required),f('rate','VNĐ / 1 USD','number',{min:1,...required})],['contractId','effectiveDate','rate'],['admin','accountant']),
 feeTypes:base('Thuế suất theo loại phí','thuế suất','TÀI CHÍNH','percent','THUE',[opt('fee','Loại phí',['rent','service','electricity','water','parking','signage','overtime'],required),f('taxRate','Thuế suất (%)','number',{min:0,max:100,...required}),f('effectiveDate','Ngày hiệu lực','date',required)],['fee','taxRate','effectiveDate'],['admin','accountant']),
 meters:base('Chỉ số điện & nước','chỉ số công tơ','VẬN HÀNH','gauge','CT',[ref('contractId','Hợp đồng','contracts',required),opt('fee','Loại công tơ',['electricity','water'],required),f('period','Kỳ (YYYY-MM)','month',required),f('startReading','Chỉ số đầu','number',{min:0,...required}),f('endReading','Chỉ số cuối','number',{min:0,...required})],['contractId','fee','period','startReading','endReading'],['admin','accountant','technician']),
 invoices:base('Hóa đơn & công nợ','hóa đơn','TÀI CHÍNH','receipt','HDON',[],['code','tenantId','period','total','paid','status'],[]),
 depositTransactions:base('Nhận & hoàn cọc','giao dịch cọc','TÀI CHÍNH','wallet','COC',[],['contractId','direction','amount','date','method'],[]),
 payments:base('Nhật ký thu tiền','khoản thu','TÀI CHÍNH','wallet','THU',[ref('invoiceId','Hóa đơn','invoices',required),f('amount','Số tiền (VNĐ)','number',{min:1,...required}),f('date','Ngày thu','date',required),opt('method','Hình thức',['Chuyển khoản','Tiền mặt','Cấn trừ cọc'],required),f('reference','Mã giao dịch / ghi chú')],['invoiceId','amount','date','method'],['admin','accountant']),
 expenses:base('Chi phí & phê duyệt','đề nghị chi','TÀI CHÍNH','credit','CHI',[f('name','Nội dung chi','text',required),ref('buildingId','Tòa nhà','buildings',required),ref('legalEntityId','Pháp nhân','legalEntities',required),opt('category','Nhóm chi',['Thuê chủ nhà','Vận hành','Điện nước','Lương','Marketing','Setup','Bảo trì'],required),f('amount','Số tiền trước thuế (VNĐ)','number',{min:1,...required}),f('taxRate','Thuế suất (%)','number',{min:0,max:100}),f('dueDate','Hạn thanh toán','date',required)],['name','buildingId','category','amount','status'],['admin','manager','accountant','staff','technician']),
 assets:base('Thiết bị kỹ thuật','thiết bị','VẬN HÀNH','tool','TB',[f('name','Tên thiết bị','text',required),ref('buildingId','Tòa nhà','buildings',required),opt('category','Loại',['PCCC','Thang máy','Điều hòa','Bơm','Hệ điện','Khác'],required),f('floor','Tầng'),f('warrantyUntil','Hết bảo hành','date'),f('nextMaintenance','Bảo trì kế tiếp','date',required),f('intervalDays','Chu kỳ (ngày)','number',{min:1,...required})],['name','buildingId','category','nextMaintenance'],['admin','manager','technician']),
 maintenance:base('Nhật ký bảo trì','lần bảo trì','VẬN HÀNH','calendar','BT',[ref('assetId','Thiết bị','assets',required),f('date','Ngày thực hiện','date',required),f('cost','Chi phí (VNĐ)','number',{min:0}),f('notes','Kết quả / ghi chú','textarea',required)],['assetId','date','cost','notes'],['admin','manager','technician']),
 tickets:base('Sự cố & yêu cầu dịch vụ','yêu cầu','VẬN HÀNH','life','SC',[f('name','Tiêu đề yêu cầu','text',required),ref('buildingId','Tòa nhà','buildings',required),ref('contractId','Hợp đồng liên quan','contracts'),opt('priority','Ưu tiên',['Thấp','Bình thường','Cao','Khẩn cấp'],required),f('description','Mô tả','textarea',required),f('assignee','Người xử lý'),f('slaHours','Cam kết xử lý (giờ)','number',{min:1}),f('serviceFee','Phí phát sinh trước thuế (VNĐ)','number',{min:0})],['code','name','buildingId','priority','status'],['admin','manager','staff','technician','tenant']),
 employees:base('Nhân sự & phòng ban','nhân sự','HIỆU SUẤT & NHÂN SỰ','users','NS',[f('name','Họ tên','text',required),opt('department','Phòng ban',['TCKT','PKD','BQL','MKT','HCNS'],required),f('position','Chức danh','text',required),f('email','Email','email'),ref('legalEntityId','Pháp nhân','legalEntities',required),f('baseSalary','Lương cơ bản (VNĐ)','number',{min:0,...required}),f('bonusCap','Thưởng tối đa (VNĐ)','number',{min:0,...required})],['name','department','position','legalEntityId','baseSalary']),
 obligations:base('Nghĩa vụ theo chức danh','nghĩa vụ','HIỆU SUẤT & NHÂN SỰ','list','NV',[f('name','Tên nghĩa vụ','text',required),f('position','Chức danh','text',required),opt('department','Phòng ban',['TCKT','PKD','BQL','MKT','HCNS'],required),opt('damage','Mức thiệt hại',['Nhẹ','Vừa','Nặng','Nghiêm trọng'],required)],['name','position','department','damage']),
 tasks:base('Công việc & hàng đợi duyệt','công việc','HIỆU SUẤT & NHÂN SỰ','check','CV',[f('name','Nội dung','text',required),ref('employeeId','Người phụ trách','employees',required),ref('obligationId','Nghĩa vụ','obligations',required),f('dueDate','Hạn hoàn thành','date',required),f('completedDate','Ngày hoàn thành','date'),f('progress','Tiến độ (%)','number',{min:0,max:100}),f('notes','Ghi chú / bàn giao','textarea')],['name','employeeId','dueDate','progress','status'],['admin','manager','staff','technician','accountant']),
 kpis:base('KPI – OKR','chỉ tiêu KPI','HIỆU SUẤT & NHÂN SỰ','target','KPI',[f('name','Chỉ tiêu','text',required),f('position','Chức danh','text',required),f('period','Kỳ đánh giá','month',required),opt('source','Nguồn dữ liệu',['approvedTasks','resolvedTickets','qualityScore','manual'],required),f('sourceNote','Người nhập / giải thích nguồn'),f('weight','Trọng số (%)','number',{min:1,max:100,...required}),f('target','Mục tiêu','number',{min:1,...required}),f('actual','Thực hiện (nguồn thủ công)','number',{min:0})],['name','position','period','source','weight','target']),
 projectFlows:base('Vòng đời & bàn giao dự án','quy trình dự án','ĐIỀU HÀNH','list','QT',[f('name','Tên quy trình','text',required),ref('buildingId','Tòa nhà','buildings',required),opt('template','Mô hình vòng đời',['Master Lease 10 năm','Gems Office 5 năm','Managed Office OUT','Managed Office IN','Setup'],required),ref('ownerId','Người phụ trách đầu tiên (PKD)','employees',required),ref('collaboratorId','Người phối hợp','employees'),f('dueDate','Hạn bước đầu tiên','date',required)],['name','buildingId','template','currentStepName','status']),
 qualityChecks:base('Chất lượng dịch vụ','phiếu chất lượng','VẬN HÀNH','check','CL',[ref('buildingId','Tòa nhà','buildings',required),ref('employeeId','Nhân sự được đánh giá','employees',required),opt('serviceRole','Vị trí dịch vụ',['An ninh','Tạp vụ','Lễ tân','Kỹ thuật'],required),f('date','Ngày đánh giá','date',required),f('score','Điểm chất lượng /100','number',{min:0,max:100,...required}),f('notes','Nhận xét / tiêu chí kiểm tra','textarea',required),f('photo','Ảnh hiện trường (PNG/JPEG/WebP, tối đa 300 KB)','image'),f('latitude','Vĩ độ GPS','number',{min:-90,max:90}),f('longitude','Kinh độ GPS','number',{min:-180,max:180})],['buildingId','employeeId','serviceRole','date','score'],['admin','manager']),
 appraisals:base('Thẩm định đầu tư','mô hình thẩm định','ĐIỀU HÀNH','chart','TD',[f('name','Tên cơ hội','text',required),opt('model','Mô hình',['Master Lease','Managed Office','Setup'],required),f('area','Diện tích cho thuê (m²)','number',{min:1,...required}),f('rentPerM2','Giá bán /m²/tháng','number',{min:1,...required}),f('ownerRent','Thuê chủ nhà/tháng','number',{min:0,...required}),f('operatingCost','Vận hành/tháng','number',{min:0,...required}),f('marketingCost','Marketing/tháng','number',{min:0}),f('setupCost','Setup ban đầu','number',{min:0,...required}),f('deposit','Cọc chủ nhà','number',{min:0}),f('freeMonths','Tháng miễn phí chủ nhà','number',{min:0,max:120}),f('occupancy','Lấp đầy ổn định (%)','number',{min:0,max:100,...required}),f('rampMonths','Tháng để đạt lấp đầy','number',{min:1,max:120,...required}),f('rentGrowth','Tăng giá bán/năm (%)','number',{min:0,max:100}),f('costGrowth','Tăng giá chủ nhà/năm (%)','number',{min:0,max:100}),f('churn','Tỷ lệ khách rời đi/tháng (%)','number',{min:0,max:100}),f('discountRate','Chiết khấu/năm (%)','number',{min:0,max:100,...required})],['name','model','area','rentPerM2','occupancy']),
 announcements:base('Thông báo nội bộ','thông báo','ĐIỀU HÀNH','bell','TBÁO',[f('name','Tiêu đề','text',required),ref('buildingId','Tòa nhà','buildings'),f('content','Nội dung','textarea',required),f('publishDate','Ngày đăng','date',required)],['name','buildingId','publishDate']),
};
export const feeLabels={rent:'Tiền thuê',service:'Phí dịch vụ',electricity:'Điện',water:'Nước',parking:'Gửi xe',signage:'Biển bảng',overtime:'Ngoài giờ'};
export const statusColors={'Đã nhận hàng':'green','Đang thuê':'green','Hiệu lực':'green','Đã duyệt':'green','Đã thu đủ':'green','Đã thanh toán':'green','Đã nghiệm thu':'green','Đã hoàn thành':'green','Trống':'gray','Đã đóng':'gray','Chưa hoàn thành':'gray','Chờ duyệt':'amber','Chờ thu':'amber','Thu một phần':'amber','Mới':'blue','Đang xử lý':'blue','Chờ nghiệm thu':'amber','Bị trả lại':'red','Quá hạn':'red','Bảo trì':'amber'};
export const dateToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
